### ISSUE TITLE
Change default camera position

### ISSUE THREAD

**Issue by cale-bradbury** [nudibranchrecords/hedron#142]
Currently the camera sits at `z: -1000` I feel that it would feel more natural if the camera was somewhere between -3 and -10. My thinking behind this is so that if the user creates a default cube (size 1) at `(0, 0, 0)` it would be visible (thinking ideally takes up 1/3rd or the height of the screen at 16:9). Not needing to scale up objects to such a massive degree would help give a more natural default perspective/apparent fov.

We definitely would want to have this in place before doing any kind of push with 0.5 (if we are to change this) as it's going to affect all existing sketches

**Comment by funwithtriangles** [comment]
Yeah I've always struggled with having a consistent "scale" between sketches. One of the issues is that in some scenes I've had to change the size of things because there have been render order bugs.  I think this was because all of my objects were too large, but I'm not sure if the same could happen if everything is too small. 

The basic [three](https://threejs.org/docs/index.html#manual/en/introduction/Creating-a-scene) example has it at 5, which might be best? Either way it should probably be documented and we actually need a neat way of dealing with the camera anyway. I'm wondering if there are some nice built in utilities for controlling it, or just a good "utility" sketch file that can be offered as a starting point for camera control (perhaps as a "core" sketch https://github.com/nudibranchrecords/hedron/issues/139).

**Comment by cale-bradbury** [comment]
Hm, following the THREE standard might be a good idea.

A utility sketch sounds like a good idea, perhaps added by default when a new scene is created.

**Comment by funwithtriangles** [comment]
Done
https://github.com/nudibranchrecords/hedron/pull/147
