### ISSUE TITLE
Base transform controls for each root object

### ISSUE THREAD

**Issue by cale-bradbury** [nudibranchrecords/hedron#144]
Often we end up having the same basic transform variables on every sketch (and for those that don't they could only benefit from their inclusion), would be good to automatically have these (position/rotation/scale x/y/z) in a sketch, perhaps under a collapsible `Transform` header. We can just apply these values to the root object (or ignore/hide these if there is no root (ie post effect), or an `ignoreTransform` tag in the config as well)

I think the UI for this could be more minimal then the sliders (especially as who are we to say what range the position should have), perhaps we could draw them with a new component type, one that focuses on a single value (`a`), that could then be 'popped out' into a slider with the minimum value being `a` and a set-able maximum (or `a` representing the mid-point, with a set-able 'spread')

**Comment by funwithtriangles** [comment]
Yes! This is actually something I've thought about before. I was wondering if we have something like this, though...

https://threejs.org/examples/misc_controls_transform.html

Which makes me think this would be very useful for custom sketches too (think multiple objects in a sketch that may need positioning, or bones that need rotating, etc). 

I'm wondering if sketches should have a new method that would be something like `updateParams` where you give new values for a param, sort of similar to the way you can return values in shots. This would be useful for updating something from inside the sketch, which we'd need to do if using visual rotation tools in the scene rather than sliders.

**Comment by funwithtriangles** [comment]
There are probably quite a few ways we could approach this. At the moment I can see two:

### Inheritance
We have a new `Sketch` class that can be extended from. This way is super simple but less transparent and perhaps not as cutomisable

```javascript
class MySketch extends Sketch {
  constructor (scene, params, meta) {
    // no need to define this.root
  }
}
```

### ControllableGroup
We create a new type of object to assign `this.root` to. Perhaps there is a better name, but let's call it `ControllableGroup` for now. It would need the instance of the sketch passed in, as well as some human readable thing so the controls appear nicely in the UI. I think I prefer this approach because you could essentially place these anywhere in your sketch, having multiple ones of them. It's also a bit more transparent (the class based approach above would essentially be doing the exact same thing under the hood).

```javascript
class MySketch {
  constructor (scene, params, meta) {
    this.root = new ControllableGroup(this, "Root Object")
  }
}
```
### Extra methods for sketches
For either approach above, we're probably going to need some new reserved methods/functions. I've already mentioned an `updateParams` one, but there will also probably need to be a `createParams` one too, where we'd be pragmatically adding to what's already defined in the config. Wowzer!

### Plugins!
The `ControllableGroup` approach (along with the new methods) could encourage third party plugins too. You could have similar things that load in glTF models into the scene and add a bunch of useful bone and animation controls without ever touching the config file and barely writing any extra code to do it. Double wowzer!

**Comment by cale-bradbury** [comment]
Yeah, I really like the `ControlableGroup` idea, I feel that could be incredibly useful! Perhaps they would only be shown when that sketch is selected, or disabled entirely from the settings window.

I'm not sure about `createParams` I could see wanting to add controls from the code, but I feel that there is more of a need to create them on the fly as opposed to having a function that gets called at a specific time. Perhaps an `createSlider(data):Slider` function in the `Sketch` class? This might get weird when saving/loading, perhaps it needs to provide a name and when you eventually call `createSlider({name:'foo'})` it sends back one populated with the saved info if it has a name match?

The nice thing about functions in the `Sketch` is that you might be able to do away with the config file entirely which could make sketches more streamlined, keep everything in one place

**Comment by cale-bradbury** [comment]
One thing I loved doing and using back in flash would be something like `addSlider({target:this.material, variable:'alpha'})` so you don't even need to worry about updating it, just bind the variable and slider together when it is defined (could have an optional `onUpdate` callback too, would save you from having to check to see if a variable changed in your update loop)

**Comment by funwithtriangles** [comment]
I think we're talking about the same thing with `createParams` and `createSlider`, no? It would be a method on `MySketch` that adds the params on the fly, so you don't need to add it to the config. For instance if you wanted to do a `for` loop to add a bunch of specific params. One thing to think about here is param group/folders, which is why this is good to go in `0.6.0`, once that stuff is done.

And yes, I think that's a great idea about params being subscribed to. dat.gui has something similar. Some of these concepts are probably going to need separating out into separate issues.

**Comment by cale-bradbury** [comment]
Right yeah, I was thinking the same thing just with an eye on the future of having more param types than sliders (have text params working on one of my branches, haha)

**Comment by funwithtriangles** [comment]
Yep! Well I think params will have a "type" option so when you `createParams` you pass that in too to generate sliders, text, vector3, etc

**Comment by funwithtriangles** [comment]
This would also be very useful for moving lights around in the scene, but also makes me wonder if you'd want something like an "add light" option, which would essentially generate the params you need again and again for each item you add. Not sure how this would work from an API perspective!
