### ISSUE TITLE
Extra LFO options

### ISSUE THREAD

**Issue by funwithtriangles** [nudibranchrecords/hedron#9]
- [x] phase
- [x] noise shape
- [ ] random shape

**Comment by funwithtriangles** [comment]
Custom text box for code based wave function (i.e. After Effects)

**Comment by funwithtriangles** [comment]
Text box has own issue now: https://github.com/nudibranchrecords/hedron/issues/115

**Comment by esnho** [comment]
Hi @funwithtriangles !

I'm improving the Noise function, I'd like to make a pull request but sincerely I cannot understand why a test fails.

I'm not used to these kind of tests so would be helpful if you help me.

I've basically changed the firm of the function that calls the LFO in order to pass the link id, this is useful with the improved OneDimensionalNoise.
Finally the returns are link based and can be used to obtain different noise oscillators around the scene ;)

Please, can you help me with the tests?

Here is the fork link: https://github.com/esnho/hedron

This is what test returns:

```
(Saga) handleInput (lfo)
    √  0. Call debounceInput
    √  1. Gets assigned links
    √  2 Get Options values (nodes)
    ×  3. get value after going through first modifier at Test.<anonymous> (D:/_p/milano-live-coding/hedron/src/store/inputs/_test/sagas.spec.js:340:5)
        { '@@redux-saga/IO': true, CALL: { context: null, fn: [Function: _default], args: [ 0.555, 'sine', 2, 0.25, undefined'id' ] } }
{ message: 'Error!' }
    √  4. Dispatches batch node update action
    √  Dispatches project error if some error
```

**Comment by funwithtriangles** [comment]
Hi @esnho. Thanks for this! Feel free to make the pull request and I can take a look, the tests are a bit of a mess at the moment and I'm thinking about disabling most of them for the time being, so don't feel disheartened about them failing! When you make the PR just make sure I have the ability to commit to the branch. :)

**Comment by esnho** [comment]
Hi @funwithtriangles ! Here's the pull, to be sure you can edit the source I've added you as collaborator :)
https://github.com/nudibranchrecords/hedron/pull/145
